services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    container_name: main
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    volumes:
      - ./main/mysql/data:/var/lib/mysql
      - ./main/mysql/log:/var/log/mysql
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: seunggu
      MYSQL_DATABASE: replication_db
      MYSQL_USER: seunggu
      MYSQL_MASTER: "true"
    networks:
      - mysql_replica_network
    ports:
      - 3306:3306
  sub1:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    container_name: sub1
    volumes:
      - ./sub1/mysql/data:/var/lib/mysql
      - ./sub1/mysql/log:/var/log/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    depends_on:
      - main
    environment:
      MYSQL_MASTER_HOST: main
      MYSQL_ROOT_PASSWORD: seunggu
      MYSQL_DATABASE: replication_db
      MYSQL_USER: seunggu
      MYSQL_PASSWORD: seunggu
      MYSQL_REPL_USER: replica_user
      MYSQL_REPL_PASSWORD: seunggu
    networks:
      - mysql_replica_network
    ports:
      - 3307:3306
  sub2:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    container_name: sub2
    volumes:
      - ./sub2/mysql/data:/var/lib/mysql
      - ./sub2/mysql/log:/var/log/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    depends_on:
      - main
    environment:
      MYSQL_MASTER_HOST: main
      MYSQL_ROOT_PASSWORD: seunggu
      MYSQL_DATABASE: replication_db
      MYSQL_USER: seunggu
      MYSQL_PASSWORD: seunggu
      MYSQL_REPL_USER: replica_user
      MYSQL_REPL_PASSWORD: seunggu
    networks:
      - mysql_replica_network
    ports:
      - 3308:3306
  sub3:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    container_name: sub3
    volumes:
      - ./sub3/mysql/data:/var/lib/mysql
      - ./sub3/mysql/log:/var/log/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    depends_on:
      - main
    environment:
      MYSQL_MASTER_HOST: main
      MYSQL_ROOT_PASSWORD: seunggu
      MYSQL_DATABASE: replication_db
      MYSQL_USER: seunggu
      MYSQL_PASSWORD: seunggu
      MYSQL_REPL_USER: replica_user
      MYSQL_REPL_PASSWORD: seunggu
    networks:
      - mysql_replica_network
    ports:
      - 3309:3306
  orchestrator:
    container_name: orchestrator
    platform: linux/x86_64
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    # image: openarkcode/orchestrator:latest
    volumes:
      - ./orchestrator.init.d:/etc/init.d
    depends_on:
      - main
    networks:
      - mysql_replica_network
    ports:
      - 3000:3000

networks:
  mysql_replica_network:
    driver: bridge
